# Generated by Django 4.2.4 on 2023-08-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='image/', upload_to='/image/')),
                ('roomno', models.CharField(max_length=50)),
                ('div', models.CharField(max_length=50)),
                ('sem', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
    ]
