# Generated by Django 4.2.4 on 2023-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineservice', '0003_faculty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='/image/', upload_to='image/'),
        ),
    ]
