# Generated by Django 4.2.4 on 2023-12-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineservice', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
