# Generated by Django 4.2.4 on 2023-10-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cno', models.IntegerField()),
                ('msg', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='/image/', upload_to='image/')),
            ],
            options={
                'db_table': 'Leaves',
            },
        ),
    ]
